import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function generatePDF(result) {
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // ---------- Colors ----------

  const primary = [37, 99, 235];
  const secondary = [99, 102, 241];
  const dark = [31, 41, 55];
  const gray = [107, 114, 128];

  // ---------- HEADER ----------

  doc.setFillColor(...primary);
  doc.rect(0, 0, pageWidth, 38, "F");

  doc.setTextColor(255, 255, 255);

  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("AI Resume Reviewer", 15, 18);

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("Professional Resume Analysis Report", 15, 28);

  // ---------- DATE ----------

  doc.setTextColor(...gray);

  doc.setFontSize(10);

  doc.text(
    `Generated: ${new Date().toLocaleString()}`,
    15,
    48
  );

  // ---------- ATS SCORE CARD ----------

  const score = result.analysis.ats_score;

  let status = "Needs Improvement";

  if (score >= 75)
    status = "Excellent";
  else if (score >= 50)
    status = "Good";

  doc.setDrawColor(...secondary);
  doc.setLineWidth(0.6);

  doc.roundedRect(15, 58, 180, 34, 4, 4);

  doc.setTextColor(...dark);

  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");

  doc.text("ATS SCORE", 22, 71);

  doc.setFontSize(26);
  doc.text(`${score}%`, 145, 73);

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");

  doc.text(status, 145, 83);

  // ---------- ATS TABLE ----------

  autoTable(doc, {
    startY: 102,

    head: [["Category", "Score"]],

    body: [
      [
        "Contact",
        `${result.analysis.breakdown.contact}/10`,
      ],

      [
        "Sections",
        `${result.analysis.breakdown.sections}/30`,
      ],

      [
        "Keywords",
        `${result.analysis.breakdown.keywords}/20`,
      ],

      [
        "Formatting",
        `${result.analysis.breakdown.formatting}/20`,
      ],
    ],

    headStyles: {
      fillColor: primary,
    },

    styles: {
      fontSize: 11,
    },
  });

  let y = doc.lastAutoTable.finalY + 12;

  // ---------- Helper ----------

  const section = (title, items) => {
    doc.setFontSize(15);
    doc.setTextColor(...primary);
    doc.setFont("helvetica", "bold");

    doc.text(title, 15, y);

    y += 8;

    doc.setTextColor(...dark);
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");

    items.forEach((item) => {
      const lines = doc.splitTextToSize(`• ${item}`, 180);

      if (y > pageHeight - 20) {
        doc.addPage();
        y = 20;
      }

      doc.text(lines, 20, y);

      y += lines.length * 6;
    });

    y += 8;
  };

  // ---------- CONTENT ----------

  section(
    "Found Keywords",
    result.analysis.matched_keywords
  );

  section(
    "Missing Keywords",
    result.analysis.missing_keywords
  );

  section(
    "Suggestions",
    result.analysis.suggestions
  );

  section(
    "Strengths",
    result.ai_analysis.strengths
  );

  section(
    "Weaknesses",
    result.ai_analysis.weaknesses
  );

  section(
    "Improved Resume Bullet Points",
    result.ai_analysis.rewritten_bullets
  );

  doc.addPage();

  y = 20;

  doc.setFontSize(18);

  doc.setTextColor(...primary);

  doc.setFont("helvetica", "bold");

  doc.text("Generated Cover Letter", 15, y);

  y += 12;

  doc.setFontSize(11);

  doc.setFont("helvetica", "normal");

  doc.setTextColor(...dark);

  const lines = doc.splitTextToSize(
    result.ai_analysis.cover_letter,
    180
  );

  doc.text(lines, 15, y);

  // ---------- FOOTER ----------

  const pages = doc.getNumberOfPages();

  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);

    doc.setDrawColor(220);

    doc.line(
      15,
      pageHeight - 12,
      pageWidth - 15,
      pageHeight - 12
    );

    doc.setFontSize(9);

    doc.setTextColor(...gray);

    doc.text(
      "Generated by AI Resume Reviewer",
      15,
      pageHeight - 6
    );

    doc.text(
      `Page ${i} of ${pages}`,
      pageWidth - 35,
      pageHeight - 6
    );
  }

  doc.save("Resume_Analysis_Report.pdf");
}